SELECT 
    D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM 
    DEVELOPERS D
WHERE 
    (D.SKILL_CODE & (SELECT S.CODE FROM SKILLCODES S WHERE NAME = "Python" LIMIT 1)) > 0 
    OR (D.SKILL_CODE & (SELECT S.CODE FROM SKILLCODES S WHERE NAME = "C#" LIMIT 1)) > 0
ORDER BY 
    1 ASC;