SELECT
O1.USER_ID, O2.PRODUCT_ID
FROM ONLINE_SALE O1
JOIN ONLINE_SALE O2
ON O1.PRODUCT_ID = O2.PRODUCT_ID AND O1.USER_ID = O2.USER_ID
GROUP BY 1, 2
HAVING COUNT(O2.PRODUCT_ID) > 1
ORDER BY 1 ASC, 2 DESC;